Hooks.once("diceSoNiceReady", (dice3d) => {
    dice3d.addSystem({ id: "KiY", name: "King in Yellow" }, false);
    dice3d.addDicePreset({
        type: "d4",
        labels: [
            "modules/kiy-dice/images/d4/d4-1.png",
            "modules/kiy-dice/images/d4/d4-2.png",
            "modules/kiy-dice/images/d4/d4-3.png",
            "modules/kiy-dice/images/d4/d4-4.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d4/d4-4e.png",
        ],
        emissive: "#ffff00",
    });
    dice3d.addDicePreset({
        type: "d6",
        labels: [
            "modules/kiy-dice/images/d6/d6-1.png",
            "modules/kiy-dice/images/d6/d6-2.png",
            "modules/kiy-dice/images/d6/d6-3.png",
            "modules/kiy-dice/images/d6/d6-4.png",
            "modules/kiy-dice/images/d6/d6-5.png",
            "modules/kiy-dice/images/d6/d6-6.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d6/d6-6e.png",
        ],
        emissive: "#ffff00",
    });
    dice3d.addDicePreset({
        type: "d8",
        labels: [
            "modules/kiy-dice/images/d8/d8-1.png",
            "modules/kiy-dice/images/d8/d8-2.png",
            "modules/kiy-dice/images/d8/d8-3.png",
            "modules/kiy-dice/images/d8/d8-4.png",
            "modules/kiy-dice/images/d8/d8-5.png",
            "modules/kiy-dice/images/d8/d8-6.png",
            "modules/kiy-dice/images/d8/d8-7.png",
            "modules/kiy-dice/images/d8/d8-8.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d8/d8-8e.png",
        ],
        emissive: "#ffff00",
    });
    dice3d.addDicePreset({
        type: "d10",
        labels: [
            "modules/kiy-dice/images/d10/d10-1.png",
            "modules/kiy-dice/images/d10/d10-2.png",
            "modules/kiy-dice/images/d10/d10-3.png",
            "modules/kiy-dice/images/d10/d10-4.png",
            "modules/kiy-dice/images/d10/d10-5.png",
            "modules/kiy-dice/images/d10/d10-6.png",
            "modules/kiy-dice/images/d10/d10-7.png",
            "modules/kiy-dice/images/d10/d10-8.png",
            "modules/kiy-dice/images/d10/d10-9.png",
            "modules/kiy-dice/images/d10/d10-0.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d10/d10-0e.png",
        ],
        emissive: "#ffff00",
    });
    dice3d.addDicePreset({
        type: "d12",
        labels: [
            "modules/kiy-dice/images/d12/d12-1.png",
            "modules/kiy-dice/images/d12/d12-2.png",
            "modules/kiy-dice/images/d12/d12-3.png",
            "modules/kiy-dice/images/d12/d12-4.png",
            "modules/kiy-dice/images/d12/d12-5.png",
            "modules/kiy-dice/images/d12/d12-6.png",
            "modules/kiy-dice/images/d12/d12-7.png",
            "modules/kiy-dice/images/d12/d12-8.png",
            "modules/kiy-dice/images/d12/d12-9.png",
            "modules/kiy-dice/images/d12/d12-10.png",
            "modules/kiy-dice/images/d12/d12-11.png",
            "modules/kiy-dice/images/d12/d12-12.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d12/d12-12e.png",
        ],
        emissive: "#ffff00",
    });
    dice3d.addDicePreset({
        type: "d20",
        labels: [
            "modules/kiy-dice/images/d20/d20-1.png",
            "modules/kiy-dice/images/d20/d20-2.png",
            "modules/kiy-dice/images/d20/d20-3.png",
            "modules/kiy-dice/images/d20/d20-4.png",
            "modules/kiy-dice/images/d20/d20-5.png",
            "modules/kiy-dice/images/d20/d20-6.png",
            "modules/kiy-dice/images/d20/d20-7.png",
            "modules/kiy-dice/images/d20/d20-8.png",
            "modules/kiy-dice/images/d20/d20-9.png",
            "modules/kiy-dice/images/d20/d20-10.png",
            "modules/kiy-dice/images/d20/d20-11.png",
            "modules/kiy-dice/images/d20/d20-12.png",
            "modules/kiy-dice/images/d20/d20-13.png",
            "modules/kiy-dice/images/d20/d20-14.png",
            "modules/kiy-dice/images/d20/d20-15.png",
            "modules/kiy-dice/images/d20/d20-16.png",
            "modules/kiy-dice/images/d20/d20-17.png",
            "modules/kiy-dice/images/d20/d20-18.png",
            "modules/kiy-dice/images/d20/d20-19.png",
            "modules/kiy-dice/images/d20/d20-20.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d20/d20-20e.png",
        ],
        emissive: "#ffff00",
    });
    dice3d.addDicePreset({
        type: "d100",
        labels: [
            "modules/kiy-dice/images/d100/d100-10.png",
            "modules/kiy-dice/images/d100/d100-20.png",
            "modules/kiy-dice/images/d100/d100-30.png",
            "modules/kiy-dice/images/d100/d100-40.png",
            "modules/kiy-dice/images/d100/d100-50.png",
            "modules/kiy-dice/images/d100/d100-60.png",
            "modules/kiy-dice/images/d100/d100-70.png",
            "modules/kiy-dice/images/d100/d100-80.png",
            "modules/kiy-dice/images/d100/d100-90.png",
            "modules/kiy-dice/images/d100/d100-100.png",
        ],
        system: "KiY",
        emissiveMaps: [
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/no_emission.png",
            "modules/kiy-dice/images/d100/d100-100e.png",
        ],
        emissive: "#ffff00",
    });
});
